spring:
  profiles:
    # 激活的配置文件
    active: dev
  # 应用
  application:
    # 名称
    name: service-center
  jmx:
    default-domain: cn.com.sinosoft.mpi
  # jsp支持
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # 资源文件
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

## mq配置
mq:
  host: localhost
  port: 5672
  exchange:
    name: mpi_exchange_index
  queue:
    index:
      name: mpi_queue_index
    result:
      name: mpi_queue_result

# 日志
logging:
  path: ./logs/mpi
  level: debug

# 服务器配置
server:
  session:
    timeout: 1800
  #压缩
  compression:
      #是否开启压缩
      enabled: true

# webservice
cxf:
  path: /ws

index:
  update:
    policy: UPDATE_LEVEL_NEW