### 开发环境

## 数据库
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.254:1521:ORCL
    username: mpi
    password: embed
    driver-class-name: oracle.jdbc.driver.OracleDriver

# 服务器
server:
  #端口
  port: 9201

# 应用配置
app:
  service:
    home: http://localhost:9201/

index:
  update:
    policy: UPDATE_LEVEL_NEW

## cas配置
cas:
  url:
    prefix: http://192.168.1.252:7776/cas
    login: ${cas.url.prefix}/login
    logout: ${cas.url.prefix}/logout

## mq配置
mq:
  host: localhost
  queue:
    name: MPI.PERSON
  exchange:
    name: ex_direct

## 服务中心配置 ##
eureka:
  instance:
    hostname: localhost
    
# 监控配置
management:
  health:
    diskspace:
      path: /Users/sinosoft