### 开发环境

spring:
  datasource: ## 数据库
    url: jdbc:oracle:thin:@192.168.1.254:1521:ORCL
    username: mpi
    password: embed
    driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    mongodb: # mongodb数据库
      uri: mongodb://mpi:embed@192.168.1.254:27017/mpi

# 服务器
server:
  #端口
  port: 9201

index:
  update:
    policy: UPDATE_LEVEL_NEW

## mq配置
mq:
  host: localhost
  exchange:
    name: ex_direct
  queue:
    index:
      name: index
    result:
      name: result

