### 开发环境

spring:
   # 数据源
  datasource:
    url: jdbc:oracle:thin:@192.168.1.254:1521:ORCL
    username: mpi
    password: embed
    driver-class-name: oracle.jdbc.driver.OracleDriver
  # mq
  rabbitmq:
    host: 192.168.1.252
    port: 5672
    listener:
      auto-startup: true
  # jpa
  jpa:
    show-sql: true

# 服务器
server:
  #端口
  port: 9201