package com.sinosoft.mpi.model;

import java.util.Date;

public class IdentifierDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String DOMAIN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.UNIQUE_SIGN
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String UNIQUE_SIGN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String DOMAIN_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_DESC
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String DOMAIN_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.PUSH_ADDR
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String PUSH_ADDR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.BOOK_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String BOOK_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String CREATE_USER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private Date CREATE_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String UPDATE_USER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private Date UPDATE_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_LEVEL
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    private String DOMAIN_LEVEL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_ID
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getDOMAIN_ID() {
        return DOMAIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_ID
     *
     * @param DOMAIN_ID the value for AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setDOMAIN_ID(String DOMAIN_ID) {
        this.DOMAIN_ID = DOMAIN_ID == null ? null : DOMAIN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UNIQUE_SIGN
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.UNIQUE_SIGN
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getUNIQUE_SIGN() {
        return UNIQUE_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UNIQUE_SIGN
     *
     * @param UNIQUE_SIGN the value for AURORA.MPI_IDENTIFIER_DOMAIN.UNIQUE_SIGN
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setUNIQUE_SIGN(String UNIQUE_SIGN) {
        this.UNIQUE_SIGN = UNIQUE_SIGN == null ? null : UNIQUE_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_TYPE
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getDOMAIN_TYPE() {
        return DOMAIN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_TYPE
     *
     * @param DOMAIN_TYPE the value for AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setDOMAIN_TYPE(String DOMAIN_TYPE) {
        this.DOMAIN_TYPE = DOMAIN_TYPE == null ? null : DOMAIN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_DESC
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_DESC
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getDOMAIN_DESC() {
        return DOMAIN_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_DESC
     *
     * @param DOMAIN_DESC the value for AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_DESC
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setDOMAIN_DESC(String DOMAIN_DESC) {
        this.DOMAIN_DESC = DOMAIN_DESC == null ? null : DOMAIN_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.PUSH_ADDR
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.PUSH_ADDR
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getPUSH_ADDR() {
        return PUSH_ADDR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.PUSH_ADDR
     *
     * @param PUSH_ADDR the value for AURORA.MPI_IDENTIFIER_DOMAIN.PUSH_ADDR
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setPUSH_ADDR(String PUSH_ADDR) {
        this.PUSH_ADDR = PUSH_ADDR == null ? null : PUSH_ADDR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.BOOK_TYPE
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.BOOK_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getBOOK_TYPE() {
        return BOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.BOOK_TYPE
     *
     * @param BOOK_TYPE the value for AURORA.MPI_IDENTIFIER_DOMAIN.BOOK_TYPE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setBOOK_TYPE(String BOOK_TYPE) {
        this.BOOK_TYPE = BOOK_TYPE == null ? null : BOOK_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_USER_ID
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getCREATE_USER_ID() {
        return CREATE_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_USER_ID
     *
     * @param CREATE_USER_ID the value for AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setCREATE_USER_ID(String CREATE_USER_ID) {
        this.CREATE_USER_ID = CREATE_USER_ID == null ? null : CREATE_USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_DATE
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public Date getCREATE_DATE() {
        return CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_DATE
     *
     * @param CREATE_DATE the value for AURORA.MPI_IDENTIFIER_DOMAIN.CREATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setCREATE_DATE(Date CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_USER_ID
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getUPDATE_USER_ID() {
        return UPDATE_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_USER_ID
     *
     * @param UPDATE_USER_ID the value for AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_USER_ID
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setUPDATE_USER_ID(String UPDATE_USER_ID) {
        this.UPDATE_USER_ID = UPDATE_USER_ID == null ? null : UPDATE_USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_DATE
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public Date getUPDATE_DATE() {
        return UPDATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_DATE
     *
     * @param UPDATE_DATE the value for AURORA.MPI_IDENTIFIER_DOMAIN.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setUPDATE_DATE(Date UPDATE_DATE) {
        this.UPDATE_DATE = UPDATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_LEVEL
     *
     * @return the value of AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_LEVEL
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public String getDOMAIN_LEVEL() {
        return DOMAIN_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_LEVEL
     *
     * @param DOMAIN_LEVEL the value for AURORA.MPI_IDENTIFIER_DOMAIN.DOMAIN_LEVEL
     *
     * @mbggenerated Tue Nov 20 10:27:41 CST 2012
     */
    public void setDOMAIN_LEVEL(String DOMAIN_LEVEL) {
        this.DOMAIN_LEVEL = DOMAIN_LEVEL == null ? null : DOMAIN_LEVEL.trim();
    }
}