package com.sinosoft.mpi.model;

public class IndexIdentifierRel {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_NO
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private Long COMBINE_NO;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.DOMAIN_ID
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private String DOMAIN_ID;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.MPI_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private String MPI_PK;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.FIELD_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private String FIELD_PK;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.PERSON_IDENTIFIER
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private String PERSON_IDENTIFIER;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_REC
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	private Long COMBINE_REC;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_TYPE
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	// private String COMBINE_TYPE;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_NO
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_NO
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public Long getCOMBINE_NO() {
		return COMBINE_NO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_NO
	 *
	 * @param COMBINE_NO
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_NO
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setCOMBINE_NO(Long COMBINE_NO) {
		this.COMBINE_NO = COMBINE_NO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.DOMAIN_ID
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.DOMAIN_ID
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public String getDOMAIN_ID() {
		return DOMAIN_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.DOMAIN_ID
	 *
	 * @param DOMAIN_ID
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.DOMAIN_ID
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setDOMAIN_ID(String DOMAIN_ID) {
		this.DOMAIN_ID = DOMAIN_ID == null ? null : DOMAIN_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.MPI_PK
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.MPI_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public String getMPI_PK() {
		return MPI_PK;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.MPI_PK
	 *
	 * @param MPI_PK
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.MPI_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setMPI_PK(String MPI_PK) {
		this.MPI_PK = MPI_PK == null ? null : MPI_PK.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.FIELD_PK
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.FIELD_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public String getFIELD_PK() {
		return FIELD_PK;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.FIELD_PK
	 *
	 * @param FIELD_PK
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.FIELD_PK
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setFIELD_PK(String FIELD_PK) {
		this.FIELD_PK = FIELD_PK == null ? null : FIELD_PK.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.PERSON_IDENTIFIER
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.PERSON_IDENTIFIER
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public String getPERSON_IDENTIFIER() {
		return PERSON_IDENTIFIER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.PERSON_IDENTIFIER
	 *
	 * @param PERSON_IDENTIFIER
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.PERSON_IDENTIFIER
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setPERSON_IDENTIFIER(String PERSON_IDENTIFIER) {
		this.PERSON_IDENTIFIER = PERSON_IDENTIFIER == null ? null : PERSON_IDENTIFIER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_REC
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_REC
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public Long getCOMBINE_REC() {
		return COMBINE_REC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_REC
	 *
	 * @param COMBINE_REC
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_REC
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	public void setCOMBINE_REC(Long COMBINE_REC) {
		this.COMBINE_REC = COMBINE_REC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_TYPE
	 *
	 * @return the value of AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_TYPE
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	/*
	 * public String getCOMBINE_TYPE() { return COMBINE_TYPE; }
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_TYPE
	 *
	 * @param COMBINE_TYPE
	 *            the value for AURORA.MPI_INDEX_IDENTIFIER_REL.COMBINE_TYPE
	 *
	 * @mbggenerated Tue Nov 27 09:32:38 CST 2012
	 */
	/*
	 * public void setCOMBINE_TYPE(String COMBINE_TYPE) { this.COMBINE_TYPE =
	 * COMBINE_TYPE == null ? null : COMBINE_TYPE.trim(); }
	 */
}