package com.sinosoft.mpi.model;

import java.math.BigDecimal;

public class MpiCombineLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_REC_LEV
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    private Short COMBINE_REC_LEV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_NO
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    private BigDecimal COMBINE_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_FIELD
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    private String COMBINE_FIELD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AURORA.MPI_COMBINE_LEVEL.SRC_LEVEL
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    private Short SRC_LEVEL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_REC_LEV
     *
     * @return the value of AURORA.MPI_COMBINE_LEVEL.COMBINE_REC_LEV
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public Short getCOMBINE_REC_LEV() {
        return COMBINE_REC_LEV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_REC_LEV
     *
     * @param COMBINE_REC_LEV the value for AURORA.MPI_COMBINE_LEVEL.COMBINE_REC_LEV
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public void setCOMBINE_REC_LEV(Short COMBINE_REC_LEV) {
        this.COMBINE_REC_LEV = COMBINE_REC_LEV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_NO
     *
     * @return the value of AURORA.MPI_COMBINE_LEVEL.COMBINE_NO
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public BigDecimal getCOMBINE_NO() {
        return COMBINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_NO
     *
     * @param COMBINE_NO the value for AURORA.MPI_COMBINE_LEVEL.COMBINE_NO
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public void setCOMBINE_NO(BigDecimal COMBINE_NO) {
        this.COMBINE_NO = COMBINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_FIELD
     *
     * @return the value of AURORA.MPI_COMBINE_LEVEL.COMBINE_FIELD
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public String getCOMBINE_FIELD() {
        return COMBINE_FIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_COMBINE_LEVEL.COMBINE_FIELD
     *
     * @param COMBINE_FIELD the value for AURORA.MPI_COMBINE_LEVEL.COMBINE_FIELD
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public void setCOMBINE_FIELD(String COMBINE_FIELD) {
        this.COMBINE_FIELD = COMBINE_FIELD == null ? null : COMBINE_FIELD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AURORA.MPI_COMBINE_LEVEL.SRC_LEVEL
     *
     * @return the value of AURORA.MPI_COMBINE_LEVEL.SRC_LEVEL
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public Short getSRC_LEVEL() {
        return SRC_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AURORA.MPI_COMBINE_LEVEL.SRC_LEVEL
     *
     * @param SRC_LEVEL the value for AURORA.MPI_COMBINE_LEVEL.SRC_LEVEL
     *
     * @mbggenerated Wed Nov 21 19:35:30 CST 2012
     */
    public void setSRC_LEVEL(Short SRC_LEVEL) {
        this.SRC_LEVEL = SRC_LEVEL;
    }
}