spring:
  profiles:
    # 激活的配置文件
    active: dev
  # 应用
  application:
    # 名称
    name: service-center
  jmx:
    default-domain: cn.com.sinosoft.mpi
  boot:
    # spring-boot-amin
    admin:
      discovery:
        converter:
          # 上下文路径
          management-context-path: /actuator
  # jsp支持
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # 资源文件
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

## cas配置
cas:
  url:
    ignore: /ws/*|/service/

# 日志
logging:
  path: ./logs/mpi
  level: debug

# 服务器配置
server:
  session:
    timeout: 1800
  #压缩
  compression:
      #是否开启压缩
      enabled: true

# webservice
cxf:
  path: /ws

# 网关配置zuul

## 服务中心配置 ##
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  # 控制台
  dashboard:
    # 路径-默认/
    path: /eurekawebui
  client:
    # 获取注册信息时间间隔-默认30
    registryFetchIntervalSeconds: 10
    # 是否注册自身-默认true
    registerWithEureka: false
    # 是否从服务端获取注册信息-默认true
    fetchRegistry: false
    # 注册中心地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# ----------------------------------------
# 监控配置
# ----------------------------------------
# ENDPOINTS
endpoints:
  enabled: false
  actuator:
    enabled: true
    path: /ep/actuator
    sensitive: false
  docs:
    curies:
      enabled: true
    enabled: true
    path: /ep/docs
    sensitive: false

# MANAGEMENT HTTP SERVER
management:
  context-path: /actuator
  add-application-context-header: true
  security:
    enabled: false
    roles: ADMIN
    sessions: stateless
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
      path: D:\\
      threshold: 0
    elasticsearch:
      enabled: false
      response-timeout: 1000
    jms:
      enabled: true
    mail:
      enabled: true
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP